TestSuite[{
	"Unit/ObjectQ.mt",
	"Unit/Super.mt",
	"Unit/getInheritanceChain.mt",
	"Unit/Object.mt",
	"Unit/WithOrdinaryObjectSet.mt",
	"Unit/SetSuper.mt",
	"Unit/withBoundSelf.mt",
	"Unit/setMember.mt",
	"Unit/bindMember.mt",
	"Unit/unsetMember.mt",
	"Unit/DeclareObject.mt"
	,
	"Integration/ObjectDeclaration.mt",
	"Integration/ParentChanging.mt",
	"Integration/MembersNoInheritance.mt",
	"Integration/MembersOneLevelInheritance.mt",
	"Integration/MembersTwoLevelInheritance.mt",
	"Integration/MembersExplicitSelf.mt",
	"Integration/SettersNoInheritance.mt",
	"Integration/SettersOneLevelInheritance.mt",
	"Integration/ProtectedObjects.mt"
}]