TestSuite[{
	"ObjectDeclaration.mt",
	"ParentChanging.mt",
	"MembersNoInheritance.mt",
	"MembersOneLevelInheritance.mt",
	"MembersTwoLevelInheritance.mt",
	"MembersExplicitSelf.mt",
	"ProtectedObjects.mt"
}]